name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer and Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libsqlite3-dev libgdbm-dev libssl-dev libffi-dev cmake libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav libmtdev-dev xclip xsel libjpeg-dev
          pip3 install --user --upgrade buildozer Cython==0.29.36 virtualenv

      - name: Build APK with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          buildozer init
          
          # অ্যান্ড্রয়েড এসডিকে লাইসেন্স অটোমেটিক অ্যাকসেপ্ট করার কমান্ড
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo -e "\n893547e6f21ba2d96111d61365668a713b91010e\n24333f1a63b6b8211e0012f12cccf1a5f9eeee01\n84831b9409646a918e30573bab4c9c91346d8abd" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license
          
          # লাইসেন্স পুরোপুরি ইয়েস (yes) করার জন্য ফোর্স রান
          yes | buildozer -v android debug
          
      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: bin/*.apk
